# Site settings
#title: CaoTianze的博客
#email: xxxx@qq.com
description: "Java工程师,H3C"
baseurl: "http://www.cnblogs.com/grass-cao/" # the subpath of your site, e.g. /blog/
#url: "http://www.cnblogs.com/grass-cao/" # the base hostname & protocol for your site
#twitter_username: 
github_username: CaoTianze  

# Build settings
markdown: kramdown
